version: "3"
services:
  nginx_node1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./index-node1.html:/usr/share/nginx/html/index.html
    networks:
        static-network:
  nginx_node2:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./index-node2.html:/usr/share/nginx/html/index.html
    networks:
        static-network:
  loadbalancer_node:
    image: haproxy:1.7-alpine
    depends_on:
      - nginx_node1
      - nginx_node2
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    cap_add: 
        - NET_ADMIN
    networks:
      - static-network
  puppet_pro:
    build:
     context: ./
     dockerfile: puppet_Dockerfile
     



networks:
  static-network:
