version: "3"
services:
  nginx_node1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./index-node1.html:/usr/share/nginx/html/index.html
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  nginx_node2:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./index-node2.html:/usr/share/nginx/html/index.html
    networks:
      static-network:
        ipv4_address: 172.20.128.3
  proxy_node1:
    build:
      context: ./
      dockerfile: ./proxy_Dockerfile
    ports:
      - 8000:6301
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./keepalived-master.conf:/etc/keepalived/keepalived.conf
    networks:
        static-network:
          ipv4_address: 172.20.128.4
    cap_add: 
        - NET_ADMIN
  proxy_node2:
    build:
      context: ./
      dockerfile: ./proxy_Dockerfile
    volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        - ./keepalived-slave.conf:/etc/keepalived/keepalived.conf
    networks:
        static-network:
          ipv4_address: 172.20.128.5
    cap_add: 
        - NET_ADMIN      

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24